### ISSUE TITLE
Mongoose's default connection logic is deprecated as of 4.11.0

### ISSUE THREAD

**Issue by jhsware** [KTH/kth-node-mongo#1]
Mongoose's default connection logic is deprecated as of 4.11.0. Please opt in to the new connection logic using the useMongoClient option, but make sure you test your connections first if you're upgrading an existing codebase
http://mongoosejs.com/docs/connections.html#use-mongo-client

**Comment by wonkyung** [comment]
This is obsolete. We are now using v6
